---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: nginx-test
  labels:
    App: od-amd
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 20%
  selector:
    matchLabels:
      App: od-amd
  replicas: 1 
  template:
    metadata:
      labels:
        App: od-amd
    spec:
      #schedulerName: custom-scheduler-eks
      terminationGracePeriodSeconds: 40
      containers:
      - name: nginx-app-memory
        image: public.ecr.aws/docker/library/nginx:stable-perl@sha256:efafee95d6f5c583c2601b7da4fbb65c8cc1e6c08ccb5fad83ad2442f07e6001
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "64Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 80
        name: kube-second-scheduler
        ports:
        - containerPort: 80
