apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "custom-scheduler-eks.fullname" . }}-config
  namespace: {{ .Values.nameSpace }}
data:
  custom-scheduler-eks-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - pluginConfig:
          - args:
              apiVersion: kubescheduler.config.k8s.io/v1
              kind: NodeResourcesFitArgs
              scoringStrategy:
                  resources:
                      - name: cpu
                        weight: 1
                      - name: memory
                        weight: 1
                  type: MostAllocated
            name: NodeResourcesFit
        {{- with .Values.plugins }}
        plugins:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        schedulerName: {{ .Values.schedulerName }}
    {{- if .Values.leaderElection.enabled }}
    leaderElection:
      leaderElect: true
      resourceNamespace: {{ .Values.nameSpace }}
      resourceName: {{ .Values.schedulerName }}
    {{ else }}
    leaderElection:
      leaderElect: false
    {{- end }}