apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "custom-scheduler-eks.fullname" . }}
  namespace: {{ .Values.nameSpace }}
  labels:
    component: custom-scheduler-eks
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  {{- if .Values.leaderElection.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{ else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      component: custom-scheduler-eks
      chart: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: custom-scheduler-eks
        chart: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "custom-scheduler-eks.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command:
          - /usr/local/bin/kube-scheduler
          - --bind-address=0.0.0.0
          - --config=/etc/kubernetes/custom-k8s-scheduler/custom-scheduler-eks-config.yaml
          - --v={{ .Values.logLevel }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ index .Values.image.tags .Values.eksVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
